; Landmarks indexes (see data/maps/landmarks.asm)
	const_def
	const SPECIAL_MAP        ; 00
; Johto landmarks
	const GEMROOT_TOWN       ; 01
	const ROUTE_1            ; 02
	const GLITTERVINE_TOWN   ; 03
	const ROUTE_2            ; 04
	const MOONFLOWER_CITY    ; 05
	const ROUTE_3            ; 06
	const OVERCAST_GROVE     ; 07
	const MARIGOLD_CAVE      ; 08
	const MARIGOLD_PORT		 ; 09
	const BLOSSOM_CITY       ; 10
	const MOUNTAIN_PASS      ; 11
	const GRANITE_VILLAGE    ; 12
DEF KANTO_LANDMARK EQU const_value
	const SPROUT_TOWER       ; 07
	const ROUTE_31           ; 05
	const RUINS_OF_ALPH      ; 08
	const ROUTE_32           ; 09
	const ROUTE_32_COAST     ; 0a
	const UNION_CAVE         ; 0b
	const AZALEA_TOWN        ; 0d
	const SLOWPOKE_WELL      ; 0e
	const ILEX_FOREST        ; 0f
	const ROUTE_34           ; 10
	const ROUTE_34_COAST     ; 11
	const STORMY_BEACH       ; 12
	const MURKY_SWAMP        ; 13
	const GOLDENROD_CITY     ; 14
	const RADIO_TOWER        ; 15
	const GOLDENROD_HARBOR   ; 16
	const MAGNET_TUNNEL      ; 17
	const ROUTE_35           ; 18
	const ROUTE_35_COAST     ; 19
	const NATIONAL_PARK      ; 1a
	const ROUTE_36           ; 1b
	const ROUTE_37           ; 1c
	const ECRUTEAK_CITY      ; 1d
	const BELLCHIME_TRAIL    ; 1e
	const TIN_TOWER          ; 1f
	const BURNED_TOWER       ; 20
	const ROUTE_38           ; 21
	const ROUTE_39           ; 22
	const RUGGED_ROAD        ; 23
	const SNOWTOP_MOUNTAIN   ; 24
	const OLIVINE_CITY       ; 25
	const LIGHTHOUSE         ; 26
	const ROUTE_40           ; 27
	const BATTLE_TOWER       ; 28
	const WHIRL_ISLANDS      ; 29
	const ROUTE_41           ; 2a
	const CIANWOOD_CITY      ; 2b
	const CLIFF_EDGE_GATE    ; 2c
	const ROUTE_47           ; 2d
	const CLIFF_CAVE         ; 2e
	const ROUTE_48           ; 2f
	const YELLOW_FOREST      ; 30
	const QUIET_CAVE         ; 31
	const ROUTE_42           ; 32
	const MT_MORTAR          ; 33
	const MAHOGANY_TOWN      ; 34
	const ROUTE_43           ; 35
	const LAKE_OF_RAGE       ; 36
	const ROUTE_44           ; 37
	const ICE_PATH           ; 38
	const DRAGONS_DEN        ; 3a
	const DARK_CAVE          ; 3c
	const SILVER_CAVE        ; 3e
	const FAST_SHIP          ; 3f
	const SINJOH_RUINS       ; 40
	const MYSTRI_STAGE       ; 41
	const PALLET_TOWN        ; 44
	const VIRIDIAN_CITY      ; 46
	const ROUTE_30            ; 47
	const VIRIDIAN_FOREST    ; 48
	const PEWTER_CITY        ; 49
	const MT_MOON            ; 4b
	const ROUTE_4            ; 4c
	const ROUTE_24           ; 4f
	const ROUTE_25           ; 50
	const ROUTE_5            ; 52
	const UNDERGROUND        ; 53
	const ROUTE_6            ; 54
	const VERMILION_CITY     ; 55
	const DIGLETTS_CAVE      ; 56
	const ROUTE_7            ; 57
	const ROUTE_8            ; 58
	const ROUTE_9            ; 59
	const ROUTE_10           ; 5a
	const ROCK_TUNNEL        ; 5b
	const DIM_CAVE           ; 5d
	const LAVENDER_TOWN      ; 5e
	const LAV_RADIO_TOWER    ; 5f
	const SOUL_HOUSE         ; 60
	const CELADON_CITY       ; 61
	const SAFFRON_CITY       ; 63
	const ROUTE_11           ; 64
	const ROUTE_12           ; 65
	const ROUTE_13           ; 66
	const ROUTE_14           ; 67
	const ROUTE_15           ; 68
	const LUCKY_ISLAND       ; 69
	const ROUTE_16           ; 6a
	const ROUTE_17           ; 6b
	const ROUTE_18           ; 6c
	const FUCHSIA_CITY       ; 6d
	const SAFARI_ZONE        ; 6e
	const URAGA_CHANNEL      ; 6f
	const SCARY_CAVE         ; 70
	const ROUTE_19           ; 71
	const ROUTE_20           ; 72
	const SEAFOAM_ISLANDS    ; 73
	const CINNABAR_ISLAND    ; 74
	const POKEMON_MANSION    ; 75
	const CINNABAR_VOLCANO   ; 76
	const ROUTE_21           ; 77
	const ROUTE_22           ; 78
	const ROUTE_27           ; 79
	const TOHJO_FALLS        ; 7a
	const ROUTE_26           ; 7b
	const POKEMON_LEAGUE     ; 7c
	const ROUTE_23           ; 7d
	const VICTORY_ROAD       ; 7e
	const INDIGO_PLATEAU     ; 7f
	const ROUTE_28           ; 80
	const CINNABAR_LAB       ; 81
DEF SHAMOUTI_LANDMARK EQU const_value
	const SHAMOUTI_ISLAND    ; 82
	const BEAUTIFUL_BEACH    ; 83
	const ROCKY_BEACH        ; 84
	const NOISY_FOREST       ; 85
	const SHRINE_RUINS       ; 86
	const SHAMOUTI_TUNNEL    ; 87
	const WARM_BEACH         ; 88
	const SHAMOUTI_COAST     ; 89
	const FIRE_ISLAND        ; 8a
	const ICE_ISLAND         ; 8b
	const LIGHTNING_ISLAND   ; 8c
	const ROUTE_49           ; 8d
	const VALENCIA_ISLAND    ; 8e
	const NAVEL_ROCK         ; 8f
	const FARAWAY_ISLAND     ; 90
DEF NUM_LANDMARKS EQU const_value

; used in CaughtData
DEF LANDMARK_EVENT EQU $ff

; Regions
	const_def
	const JOHTO_REGION  ; 0
	const KANTO_REGION  ; 1
	const ORANGE_REGION ; 2
DEF NUM_REGIONS EQU const_value
