; Generated by Siren
; Source: goodra.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_goodra:
	channel_count 3
	channel 5, Cry_goodra_Ch5
	channel 6, Cry_goodra_Ch6
	channel 8, Cry_goodra_Ch8

Cry_goodra_Ch5:
	duty_cycle 2
	square_note 1, 0, 8, 0
	duty_cycle 1
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 3, 8, 1827
	square_note 1, 13, 8, 1174
	square_note 1, 12, 8, 1174
	square_note 1, 12, 8, 1174
	square_note 1, 11, 8, 1463
	square_note 1, 12, 8, 1399
	duty_cycle 1
	square_note 1, 12, 8, 1548
	duty_cycle 3
	square_note 1, 12, 8, 1590
	duty_cycle 1
	square_note 1, 12, 8, 1430
	square_note 1, 11, 8, 1430
	duty_cycle 2
	square_note 1, 11, 8, 1511
	duty_cycle 1
	square_note 1, 12, 8, 1473
	square_note 1, 12, 8, 1540
	duty_cycle 2
	square_note 1, 11, 8, 1832
	duty_cycle 3
	square_note 1, 11, 8, 1566
	duty_cycle 1
	square_note 1, 10, 8, 1412
	duty_cycle 2
	square_note 1, 10, 8, 1577
	duty_cycle 3
	square_note 1, 10, 8, 1519
	duty_cycle 1
	square_note 1, 10, 8, 1524
	duty_cycle 3
	square_note 1, 11, 8, 1519
	duty_cycle 2
	square_note 1, 9, 8, 1784
	square_note 1, 11, 8, 1528
	duty_cycle 1
	square_note 1, 10, 8, 1540
	square_note 1, 10, 8, 1540
	square_note 1, 11, 8, 1515
	duty_cycle 2
	square_note 1, 10, 8, 1599
	duty_cycle 1
	square_note 1, 10, 8, 1528
	square_note 1, 11, 8, 1372
	square_note 1, 11, 8, 1478
	duty_cycle 2
	square_note 1, 12, 8, 1532
	square_note 1, 11, 8, 1493
	duty_cycle 0
	square_note 1, 6, 8, 1771
	duty_cycle 2
	square_note 1, 2, 8, 1934
	square_note 1, 0, 8, 0
	duty_cycle 3
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 0, 8, 0
	duty_cycle 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	duty_cycle 1
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 0, 8, 0
	duty_cycle 1
	square_note 1, 0, 8, 0
	duty_cycle 3
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	duty_cycle 0
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 0, 0, 8, 0
	sound_ret

Cry_goodra_Ch6:
	duty_cycle 2
	square_note 1, 0, 8, 0
	duty_cycle 3
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 1, 8, 1733
	square_note 1, 7, 8, 1544
	duty_cycle 0
	square_note 1, 4, 8, 1559
	duty_cycle 2
	square_note 1, 7, 8, 1566
	square_note 1, 6, 8, 1696
	square_note 1, 4, 8, 1746
	duty_cycle 0
	square_note 1, 7, 8, 1742
	square_note 1, 7, 8, 1800
	square_note 1, 5, 8, 1793
	duty_cycle 2
	square_note 1, 5, 8, 1805
	duty_cycle 0
	square_note 1, 4, 8, 1803
	duty_cycle 2
	square_note 1, 5, 8, 1791
	square_note 1, 5, 8, 1771
	square_note 1, 7, 8, 1775
	square_note 1, 0, 8, 0
	square_note 1, 6, 8, 1788
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 6, 8, 1820
	duty_cycle 1
	square_note 1, 5, 8, 1809
	square_note 1, 5, 8, 1617
	duty_cycle 3
	square_note 1, 4, 8, 1586
	square_note 1, 3, 8, 1590
	duty_cycle 1
	square_note 1, 6, 8, 1611
	duty_cycle 0
	square_note 1, 4, 8, 1806
	square_note 1, 4, 8, 1808
	duty_cycle 2
	square_note 1, 4, 8, 1770
	square_note 1, 4, 8, 1747
	duty_cycle 1
	square_note 1, 6, 8, 1658
	duty_cycle 0
	square_note 1, 5, 8, 1660
	duty_cycle 2
	square_note 1, 7, 8, 1740
	duty_cycle 0
	square_note 1, 3, 8, 1834
	duty_cycle 2
	square_note 1, 1, 8, 1954
	square_note 1, 0, 8, 0
	duty_cycle 3
	square_note 1, 0, 8, 0
	duty_cycle 0
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 0, 8, 0
	duty_cycle 0
	square_note 1, 0, 8, 0
	duty_cycle 1
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 0, 8, 0
	duty_cycle 3
	square_note 1, 0, 8, 0
	duty_cycle 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_goodra_Ch8:
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 2, 8, 44
	noise_note 1, 4, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 4, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 2, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 2, 8, 44
	noise_note 1, 2, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 2, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 2, 8, 44
	noise_note 1, 2, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 2, 8, 44
	noise_note 1, 2, 8, 44
	noise_note 1, 2, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 3, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 0, 0, 8, 44
	sound_ret
